// <auto-generated />
using System;
using ClassRoomManagementSystemServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassRoomManagementSystemServer.Migrations
{
    [DbContext(typeof(ClassroomManagementContext))]
    [Migration("20231124053756_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Building", b =>
                {
                    b.Property<string>("BuildingName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("building_name");

                    b.Property<uint>("NumberClassrooms")
                        .HasColumnType("int unsigned")
                        .HasColumnName("number_classrooms");

                    b.HasKey("BuildingName")
                        .HasName("PRIMARY");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Classroom", b =>
                {
                    b.Property<uint>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("classroom_id");

                    b.Property<TimeOnly>("BackoutHours")
                        .HasColumnType("time")
                        .HasColumnName("backout_hours");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("building_name");

                    b.Property<uint>("Capacity")
                        .HasColumnType("int unsigned")
                        .HasColumnName("capacity");

                    b.Property<uint>("RoomNumber")
                        .HasColumnType("int unsigned")
                        .HasColumnName("room_number");

                    b.HasKey("ClassroomId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BuildingName" }, "Classroom_FK");

                    b.ToTable("Classroom", (string)null);
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Course", b =>
                {
                    b.Property<uint>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("course_id");

                    b.Property<uint>("Credits")
                        .HasColumnType("int unsigned")
                        .HasColumnName("credits");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("department_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("CourseId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DepartmentName" }, "Course_FK");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Department", b =>
                {
                    b.Property<string>("DepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("department_name");

                    b.Property<float?>("Budget")
                        .HasColumnType("float")
                        .HasColumnName("budget");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("building_name");

                    b.HasKey("DepartmentName")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BuildingName" }, "Department_FK");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Equipment", b =>
                {
                    b.Property<uint>("EquipmentId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("equipment_id");

                    b.Property<uint>("ClassroomId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("classroom_id");

                    b.Property<uint>("CourseId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("course_id");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("equipment_type");

                    b.HasKey("EquipmentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClassroomId" }, "Equipment_FK");

                    b.HasIndex(new[] { "CourseId" }, "Equipment_FK_1");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Request", b =>
                {
                    b.Property<uint>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("request_id");

                    b.Property<uint>("ClassroomId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("classroom_id");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("department_name");

                    b.Property<string>("Descritption")
                        .HasColumnType("text");

                    b.HasKey("RequestId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClassroomId" }, "Requests_FK");

                    b.HasIndex(new[] { "DepartmentName" }, "Requests_FK_1");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Section", b =>
                {
                    b.Property<uint>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("section_id");

                    b.Property<uint>("CourseId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("course_id");

                    b.Property<string>("Semester")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("semester");

                    b.Property<uint>("Year")
                        .HasColumnType("int unsigned")
                        .HasColumnName("year");

                    b.Property<uint>("ClassroomId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("classroom_id");

                    b.Property<uint?>("TimeSlotId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("time_slot_id");

                    b.HasKey("SectionId", "CourseId", "Semester", "Year")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0, 0 });

                    b.HasIndex(new[] { "CourseId" }, "Section_FK");

                    b.HasIndex(new[] { "ClassroomId" }, "Section_FK_1");

                    b.HasIndex(new[] { "TimeSlotId" }, "Section_FK_2");

                    b.ToTable("Section", (string)null);
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.TimeSlot", b =>
                {
                    b.Property<uint>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("time_slot_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("TimeSlotId")
                        .HasName("PRIMARY");

                    b.ToTable("Time_Slot", (string)null);
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Classroom", b =>
                {
                    b.HasOne("ClassRoomManagementSystemServer.Models.Building", "BuildingNameNavigation")
                        .WithMany("Classrooms")
                        .HasForeignKey("BuildingName")
                        .HasConstraintName("Classroom_FK");

                    b.Navigation("BuildingNameNavigation");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Course", b =>
                {
                    b.HasOne("ClassRoomManagementSystemServer.Models.Department", "DepartmentNameNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentName")
                        .HasConstraintName("Course_FK");

                    b.Navigation("DepartmentNameNavigation");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Department", b =>
                {
                    b.HasOne("ClassRoomManagementSystemServer.Models.Building", "BuildingNameNavigation")
                        .WithMany("Departments")
                        .HasForeignKey("BuildingName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Department_FK");

                    b.Navigation("BuildingNameNavigation");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Equipment", b =>
                {
                    b.HasOne("ClassRoomManagementSystemServer.Models.Classroom", "Classroom")
                        .WithMany("Equipment")
                        .HasForeignKey("ClassroomId")
                        .IsRequired()
                        .HasConstraintName("Equipment_FK");

                    b.HasOne("ClassRoomManagementSystemServer.Models.Course", "Course")
                        .WithMany("Equipment")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("Equipment_FK_1");

                    b.Navigation("Classroom");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Request", b =>
                {
                    b.HasOne("ClassRoomManagementSystemServer.Models.Classroom", "Classroom")
                        .WithMany("Requests")
                        .HasForeignKey("ClassroomId")
                        .IsRequired()
                        .HasConstraintName("Requests_FK");

                    b.HasOne("ClassRoomManagementSystemServer.Models.Department", "DepartmentNameNavigation")
                        .WithMany("Requests")
                        .HasForeignKey("DepartmentName")
                        .HasConstraintName("Requests_FK_1");

                    b.Navigation("Classroom");

                    b.Navigation("DepartmentNameNavigation");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Section", b =>
                {
                    b.HasOne("ClassRoomManagementSystemServer.Models.Classroom", "Classroom")
                        .WithMany("Sections")
                        .HasForeignKey("ClassroomId")
                        .IsRequired()
                        .HasConstraintName("Section_FK_1");

                    b.HasOne("ClassRoomManagementSystemServer.Models.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("Section_FK");

                    b.HasOne("ClassRoomManagementSystemServer.Models.TimeSlot", "TimeSlot")
                        .WithMany("Sections")
                        .HasForeignKey("TimeSlotId")
                        .HasConstraintName("Section_FK_2");

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Building", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Classroom", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Requests");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Course", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.TimeSlot", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
