// <auto-generated />
using System;
using ClassRoomManagementSystemServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassRoomManagementSystemServer.Migrations
{
    [DbContext(typeof(MydbContext))]
    [Migration("20231127230831_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb3_general_ci")
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb3");

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Classroom", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("classroom_id");

                    b.Property<TimeOnly?>("BlackoutHours")
                        .HasColumnType("time")
                        .HasColumnName("blackout_hours");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("DepartmentDepartmentName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("Department_department_name");

                    b.Property<int>("RoomNum")
                        .HasColumnType("int")
                        .HasColumnName("room_num");

                    b.HasKey("ClassroomId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DepartmentDepartmentName" }, "fk_Classroom_Department1_idx");

                    b.ToTable("classroom", (string)null);
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Course", b =>
                {
                    b.Property<string>("CourseTitle")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("course_title");

                    b.Property<float?>("Credits")
                        .HasColumnType("float")
                        .HasColumnName("credits");

                    b.Property<string>("DepartmentDepartmentName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("Department_department_name");

                    b.HasKey("CourseTitle")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DepartmentDepartmentName" }, "fk_Course_Department1_idx");

                    b.ToTable("course", (string)null);
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Department", b =>
                {
                    b.Property<string>("DepartmentName")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("department_name");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("building_name");

                    b.Property<uint?>("NumClassroom")
                        .HasColumnType("int unsigned")
                        .HasColumnName("num_classroom");

                    b.HasKey("DepartmentName")
                        .HasName("PRIMARY");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("equipment_id");

                    b.Property<int>("ClassroomClassroomId")
                        .HasColumnType("int")
                        .HasColumnName("Classroom_classroom_id");

                    b.Property<string>("CourseCourseTitle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Course_course_title");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("equipment_type");

                    b.HasKey("EquipmentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClassroomClassroomId" }, "fk_Equipment_Classroom1_idx");

                    b.HasIndex(new[] { "CourseCourseTitle" }, "fk_Equipment_Course1_idx");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<int>("ClassroomClassroomId")
                        .HasColumnType("int")
                        .HasColumnName("Classroom_classroom_id");

                    b.Property<string>("DepartmentDepartmentName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("Department_department_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("RequestId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClassroomClassroomId" }, "fk_Request_Classroom1_idx");

                    b.HasIndex(new[] { "DepartmentDepartmentName" }, "fk_Request_Department_idx");

                    b.ToTable("request", (string)null);
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<string>("CourseTitle")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("course_title");

                    b.Property<string>("Semester")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("semester");

                    b.Property<string>("Year")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("year");

                    b.Property<string>("CourseCourseTitle")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Course_course_title");

                    b.Property<int>("ClassroomClassroomId")
                        .HasColumnType("int")
                        .HasColumnName("Classroom_classroom_id");

                    b.Property<int>("TimeSlotTimeSlotId")
                        .HasColumnType("int")
                        .HasColumnName("Time_Slot_time_slot_id");

                    b.HasKey("SectionId", "CourseTitle", "Semester", "Year", "CourseCourseTitle")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0, 0, 0 });

                    b.HasIndex(new[] { "ClassroomClassroomId" }, "fk_Section_Classroom1_idx");

                    b.HasIndex(new[] { "CourseCourseTitle" }, "fk_Section_Course1_idx");

                    b.HasIndex(new[] { "TimeSlotTimeSlotId" }, "fk_Section_Time_Slot1_idx");

                    b.ToTable("section", (string)null);
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.TimeSlot", b =>
                {
                    b.Property<int>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("time_slot_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.HasKey("TimeSlotId")
                        .HasName("PRIMARY");

                    b.ToTable("time_slot", (string)null);
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Classroom", b =>
                {
                    b.HasOne("ClassRoomManagementSystemServer.Models.Department", "DepartmentDepartmentNameNavigation")
                        .WithMany("Classrooms")
                        .HasForeignKey("DepartmentDepartmentName")
                        .IsRequired()
                        .HasConstraintName("fk_Classroom_Department1");

                    b.Navigation("DepartmentDepartmentNameNavigation");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Course", b =>
                {
                    b.HasOne("ClassRoomManagementSystemServer.Models.Department", "DepartmentDepartmentNameNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentDepartmentName")
                        .IsRequired()
                        .HasConstraintName("fk_Course_Department1");

                    b.Navigation("DepartmentDepartmentNameNavigation");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Equipment", b =>
                {
                    b.HasOne("ClassRoomManagementSystemServer.Models.Classroom", "ClassroomClassroom")
                        .WithMany("Equipment")
                        .HasForeignKey("ClassroomClassroomId")
                        .IsRequired()
                        .HasConstraintName("fk_Equipment_Classroom1");

                    b.HasOne("ClassRoomManagementSystemServer.Models.Course", "CourseCourseTitleNavigation")
                        .WithMany("Equipment")
                        .HasForeignKey("CourseCourseTitle")
                        .IsRequired()
                        .HasConstraintName("fk_Equipment_Course1");

                    b.Navigation("ClassroomClassroom");

                    b.Navigation("CourseCourseTitleNavigation");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Request", b =>
                {
                    b.HasOne("ClassRoomManagementSystemServer.Models.Classroom", "ClassroomClassroom")
                        .WithMany("Requests")
                        .HasForeignKey("ClassroomClassroomId")
                        .IsRequired()
                        .HasConstraintName("fk_Request_Classroom1");

                    b.HasOne("ClassRoomManagementSystemServer.Models.Department", "DepartmentDepartmentNameNavigation")
                        .WithMany("Requests")
                        .HasForeignKey("DepartmentDepartmentName")
                        .IsRequired()
                        .HasConstraintName("fk_Request_Department");

                    b.Navigation("ClassroomClassroom");

                    b.Navigation("DepartmentDepartmentNameNavigation");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Section", b =>
                {
                    b.HasOne("ClassRoomManagementSystemServer.Models.Classroom", "ClassroomClassroom")
                        .WithMany("Sections")
                        .HasForeignKey("ClassroomClassroomId")
                        .IsRequired()
                        .HasConstraintName("fk_Section_Classroom1");

                    b.HasOne("ClassRoomManagementSystemServer.Models.Course", "CourseCourseTitleNavigation")
                        .WithMany("Sections")
                        .HasForeignKey("CourseCourseTitle")
                        .IsRequired()
                        .HasConstraintName("fk_Section_Course1");

                    b.HasOne("ClassRoomManagementSystemServer.Models.TimeSlot", "TimeSlotTimeSlot")
                        .WithMany("Sections")
                        .HasForeignKey("TimeSlotTimeSlotId")
                        .IsRequired()
                        .HasConstraintName("fk_Section_Time_Slot1");

                    b.Navigation("ClassroomClassroom");

                    b.Navigation("CourseCourseTitleNavigation");

                    b.Navigation("TimeSlotTimeSlot");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Classroom", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Requests");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Course", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.Department", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Courses");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("ClassRoomManagementSystemServer.Models.TimeSlot", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
